import { Hono } from 'hono'
import type { AppEnv } from '../../types/env'
import { uploadVideoChunk, finalizeChunkedVideoUpload } from '../../lib/media/video-upload'
import { generateVideoThumbnail } from '../../lib/media/video-thumbnail'
import { orchestrateVideoTranscode } from '../../lib/media/video-transcode'
import { queryAll } from '../../lib/media/db'

const route = new Hono<AppEnv>()

route.post('/', async (c) => {
  const body = await c.req.parseBody()
  const file = body.file
  if (!(file instanceof File)) return c.json({ error: 'file_required' }, 400)
  const uploadId = typeof body.uploadId === 'string' ? body.uploadId : crypto.randomUUID()
  const part = await uploadVideoChunk(c.env, file, uploadId, 1)
  const finalized = await finalizeChunkedVideoUpload(c.env, file.name, file.type || 'video/mp4', [part])
  const thumb = await generateVideoThumbnail(c.env, `/r2/video/${finalized.manifestKey}`)
  const transcode = await orchestrateVideoTranscode(finalized.manifestKey)
  const id = crypto.randomUUID()
  if (c.env.DB) {
    await c.env.DB.prepare(`INSERT INTO videos (id, asset_key, title, mime, size, duration_seconds, stream_url, thumbnail_url, captions_url, uploader_id, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(id, finalized.manifestKey, String(body.title || file.name), file.type || 'video/mp4', file.size, null, transcode.manifestUrl, thumb.thumbnailUrl, null, String(body.uploaderId || 'anonymous'), new Date().toISOString())
      .run()
  }
  return c.json({ ok: true, id, uploadId, chunk: part, finalized, thumbnail: thumb.thumbnailUrl, transcode })
})

route.get('/stream/:key{.+}/manifest.m3u8', (c) => c.text('#EXTM3U\n#EXT-X-VERSION:3\n# Placeholder manifest generated by sandbox-6\n', 200, { 'Content-Type': 'application/vnd.apple.mpegurl; charset=utf-8' }))
route.post('/transcode/callback', async (c) => c.json({ ok: true, received: await c.req.json().catch(() => ({})) }))

route.get('/debug', async (c) => {
  const items = c.env.DB ? await queryAll(c.env, 'SELECT id, title, stream_url FROM videos ORDER BY created_at DESC LIMIT 5') : []
  return c.json({ items })
})

export default route
