PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS breaking_news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  link TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  active_until DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
